<?php

function ah_get_bean_catalog()
{
    return [
        'sumatra-mandheling' => [
            'id' => 'sumatra-mandheling',
            'name' => 'Sumatra Mandheling',
            'origin' => 'Aceh, Indonesia',
            'price' => '$24',
            'roast' => 'Medium roast',
            'image' => './images/products/product_1.jpg',
            'tags' => ['Dark Cocoa', 'Earthy', 'Spice'],
            'description' => 'A full-bodied cup with syrupy texture and low acidity, ideal for milk-based drinks.',
            'process' => 'Wet-hulled',
            'altitude' => '1,200-1,500 masl',
        ],
        'ethiopia-yirgacheffe' => [
            'id' => 'ethiopia-yirgacheffe',
            'name' => 'Ethiopia Yirgacheffe',
            'origin' => 'Yirgacheffe, Ethiopia',
            'price' => '$26',
            'roast' => 'Light roast',
            'image' => './images/products/product_1.jpg',
            'tags' => ['Jasmine', 'Citrus', 'Tea-like'],
            'description' => 'Floral and bright with bergamot-like aromatics and a clean, silky finish.',
            'process' => 'Washed',
            'altitude' => '1,800-2,100 masl',
        ],
        'colombia-huila' => [
            'id' => 'colombia-huila',
            'name' => 'Colombia Huila',
            'origin' => 'Huila, Colombia',
            'price' => '$23',
            'roast' => 'Medium roast',
            'image' => './images/products/product_1.jpg',
            'tags' => ['Caramel', 'Red Apple', 'Cocoa'],
            'description' => 'Balanced sweetness and gentle fruit notes that brew consistently for daily drinking.',
            'process' => 'Washed',
            'altitude' => '1,500-1,900 masl',
        ],
        'kenya-aa' => [
            'id' => 'kenya-aa',
            'name' => 'Kenya AA',
            'origin' => 'Nyeri, Kenya',
            'price' => '$27',
            'roast' => 'Light roast',
            'image' => './images/products/product_1.jpg',
            'tags' => ['Blackcurrant', 'Tomato', 'Lively'],
            'description' => 'Juicy acidity with bold berry character and a lingering structured finish.',
            'process' => 'Washed',
            'altitude' => '1,700-2,000 masl',
        ],
        'brazil-cerrado' => [
            'id' => 'brazil-cerrado',
            'name' => 'Brazil Cerrado',
            'origin' => 'Minas Gerais, Brazil',
            'price' => '$21',
            'roast' => 'Medium-dark roast',
            'image' => './images/products/product_1.jpg',
            'tags' => ['Hazelnut', 'Chocolate', 'Sweet'],
            'description' => 'Comforting profile with low acidity and nutty sweetness suited for espresso.',
            'process' => 'Natural',
            'altitude' => '900-1,250 masl',
        ],
        'guatemala-antigua' => [
            'id' => 'guatemala-antigua',
            'name' => 'Guatemala Antigua',
            'origin' => 'Antigua, Guatemala',
            'price' => '$25',
            'roast' => 'Medium roast',
            'image' => './images/products/product_1.jpg',
            'tags' => ['Cacao', 'Orange', 'Smoky'],
            'description' => 'Structured and layered cup with cocoa depth and gentle citrus brightness.',
            'process' => 'Washed',
            'altitude' => '1,500-1,700 masl',
        ],
        'rwanda-huye' => [
            'id' => 'rwanda-huye',
            'name' => 'Rwanda Huye',
            'origin' => 'Huye, Rwanda',
            'price' => '$24',
            'roast' => 'Light roast',
            'image' => './images/products/product_1.jpg',
            'tags' => ['Stone Fruit', 'Honey', 'Clean'],
            'description' => 'Elegant sweetness and bright fruit clarity with a crisp, tea-like body.',
            'process' => 'Washed',
            'altitude' => '1,700-2,000 masl',
        ],
        'panama-geisha' => [
            'id' => 'panama-geisha',
            'name' => 'Panama Geisha',
            'origin' => 'Boquete, Panama',
            'price' => '$38',
            'roast' => 'Light roast',
            'image' => './images/products/product_1.jpg',
            'tags' => ['Bergamot', 'Peach', 'Floral'],
            'description' => 'Highly aromatic and delicate, with layered florals and refined sweetness.',
            'process' => 'Washed',
            'altitude' => '1,600-1,900 masl',
        ],
        'peru-cajamarca' => [
            'id' => 'peru-cajamarca',
            'name' => 'Peru Cajamarca',
            'origin' => 'Cajamarca, Peru',
            'price' => '$22',
            'roast' => 'Medium roast',
            'image' => './images/products/product_1.jpg',
            'tags' => ['Brown Sugar', 'Citrus', 'Walnut'],
            'description' => 'Soft sweetness and mellow body with approachable citrus notes for all brew methods.',
            'process' => 'Washed',
            'altitude' => '1,400-1,900 masl',
        ],
    ];
}

function ah_get_home_beans()
{
    $catalog = ah_get_bean_catalog();
    return [
        $catalog['sumatra-mandheling'],
        $catalog['ethiopia-yirgacheffe'],
        $catalog['colombia-huila'],
    ];
}
